language: erlang
sudo: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
env:
  global:
    - CXX=g++-5
notifications:
  email: false
otp_release:
  - 18.3
install:
  - "./support/bootstrap_travis.sh"
script: ./support/travis_run_tests.sh
